### ISSUE TITLE
README - bundled demos link broken

### ISSUE THREAD

**Issue by christoph-bessei** [Alhadis/Accordion#12]
The `bundled demos`link inside the **Styling** section is broken, because there are some ` inside the:
**Current link:**
https://github.com/Alhadis/Accordion/blob/master/``demos/anim-switch.htm``
**Correct link:**
https://github.com/Alhadis/Accordion/blob/master/demos/anim-switch.htm

**Comment by Alhadis** [comment]
Good Lord, how on Earth did I manage (and miss) that one? 😂 Thanks for picking up on that!
