### ISSUE TITLE
Where is demo?

### ISSUE THREAD

**Issue by piecioshka** [Alhadis/Accordion#13]

**Comment by Alhadis** [comment]
[Here](https://github.com/Alhadis/Accordion/blob/master/demos/anim-switch.htm).

[Or here if you prefer an interactive version](https://rawgit.com/Alhadis/Accordion/master/demos/anim-switch.htm).

**Comment by piecioshka** [comment]
Thanks! 

Maybe you can add this links to special chapter in README?

**Comment by Alhadis** [comment]
I probably should... people nowadays expect to see the demo first, and details second. 😅

**Comment by Alhadis** [comment]
Crap, sorry. 😢 Completely forgot about this.

Added and released as [`v3.0.2`](https://github.com/Alhadis/Accordion/releases/tag/v3.0.2). 👍 Thanks!

**Comment by piecioshka** [comment]
Great!
