### ISSUE TITLE
Anyway to access the click event?

### ISSUE THREAD

**Issue by keshav-c** [Alhadis/Accordion#18]
I want to add buttons to the accordion header. So when there is a click event, I need to be able to figure out whether I clicked the heading or the button in the heading. How do I do this?

**Comment by Alhadis** [comment]
Use [`event.stopImmediatePropagation()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopImmediatePropagation) to prevent `click` events on buttons from bubbling up to their parent elements. So, assuming the following markup:

~~~html
<li>
	<h3>
		Foo
		<button>Bar</button>
	</h3>
	<div class="fold">
		…
	</div>
</li>
~~~

… your code might look like this:

~~~js
for(const el of document.querySelectorAll("button"))
	el.addEventListener("click", event => {
		event.stopImmediatePropagation();
		// Handle any other button behaviour here
	});
~~~

**Comment by keshav-c** [comment]
Thanks. This works.
