### ISSUE TITLE
Feature: Only open one accordion at a time, collapse others?

### ISSUE THREAD

**Issue by gregg-cbs** [Alhadis/Accordion#21]
Hello,

Somehow it must be possible to only open one accordion at a time whereby if an accordion item is open and you click to expand another accordion item, the open item closes and the clicked item expands.

Any help would be great.

Thanks!

**Comment by gregg-cbs** [comment]
Answered in: https://github.com/Alhadis/Accordion/issues/6

**Comment by Alhadis** [comment]
@gregg-cbs You aren't the first to ask about this. I'm starting to regret not adding a `modal` option to simplify such a common and obvious feature…

**Comment by gregg-cbs** [comment]
Yeah would have been a great idea, kind of expected.
Also because Bootstrap accordion does this behavior by default and a lot of devs at some point have used bootstrap.

But at least for now we have a solution.
