### ISSUE TITLE
Option to allow only one fold to be open at a time

### ISSUE THREAD

**Issue by blimpmason** [Alhadis/Accordion#6]
Is there a method I could use on the onToggle callback to collapse all other folds when one is expanded? So if you open one, any open section collapses.

**Comment by Alhadis** [comment]
Hey buddy,

Not out-of-the-box, I'm afraid. Try using this as your `onToggle` callback:

``` js
onToggle: function(target){
    target.accordion.folds.forEach(fold => {
        if(fold !== target)
            fold.open = false;
    });
}
```

I thought to include a `modal` option, but wanted the core code to be as minimal as possible. Though I should probably make a note of this snippet in the readme, since modal accordions are that common. =)

**Comment by blimpmason** [comment]
Perfect, thanks! Much appreciated.

**Comment by Alhadis** [comment]
No problem! Glad I could help. =)
